[workspace]

resolver = "2"

members = [
    "calculator",
    "tempcomp",
    "guessing_game", 
    "variables", 
    "functions", 
    "fizzbuzz"
    , "primechecker", "stopwatch", "rock_paper_scissors", "unit_converter", "fibonacci", "testing"]
